// Datos de ejemplo del modo demo (portados del original).
const now = new Date()
const P = now.getFullYear()
const F = now.getMonth()

const rawPublications = [
    {
      id: `d0`,
      proyecto: `PREVENIDOS Y ACCION`,
      fecha: new Date(P, F, 2),
      titulo: `5 consejos para una vuelta al cole sin estrés`,
      copy: `¿Preparados para el nuevo curso? Os compartimos los 5 consejos que más nos funcionan para arrancar septiembre con energía y sin agobios. 👇`,
      media: `https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `d1`,
      proyecto: `PLAZA EL CHANDRIO`,
      fecha: new Date(P, F, 4),
      titulo: `La terraza más bonita del barrio ya está abierta`,
      copy: `Sol, buena compañía y las mejores tapas de la plaza. Nuestra terraza de verano abre esta semana. ¡Te esperamos! ☀️🍻`,
      media: `https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `d2`,
      proyecto: `EL CHANDRIO GROUP`,
      fecha: new Date(P, F, 7),
      titulo: `Nos expandimos: tres nuevas ciudades en 2026`,
      copy: `El Chandrio Group da el salto. Este año abrimos en Valencia, Málaga y Bilbao. 🚀`,
      media: `https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `d4`,
      proyecto: `DEL POBLE FEST`,
      fecha: new Date(P, F, 12),
      titulo: `Programa completo del festival — ¡ya disponible!`,
      copy: `¡Por fin! Ya puedes consultar todos los artistas, horarios y escenarios. Corre que las entradas vuelan 🎪`,
      media: `https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `d5`,
      proyecto: `GASTRO LEAGUE`,
      fecha: new Date(P, F, 15),
      titulo: `Menú especial de temporada: sabores de verano`,
      copy: `Tomate de huerta, gazpacho de la abuela y nuestro arroz caldoso de bogavante. 🦞🍅`,
      media: `https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `d7`,
      proyecto: `TÁVORA TEATRO ABIERTO`,
      fecha: new Date(P, F, 22),
      titulo: `Ruta por el casco histórico: 10 rincones que no conoces`,
      copy: `Sevilla tiene secretos que solo los que saben mirar encuentran. 🗺️`,
      media: `https://images.unsplash.com/photo-1559060017-445fb9313ede?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `d8`,
      proyecto: `LA CRUZ DE CELIA`,
      fecha: new Date(P, F, 25),
      titulo: `Nueva colección Otoño — disponible desde hoy`,
      copy: `Piezas únicas hechas a mano, con tejidos naturales. 🍂✨`,
      media: `https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `d9`,
      proyecto: `GASTRO LEAGUE`,
      fecha: new Date(P, F, 9),
      titulo: `El postre del mes: tarta de queso con membrillo`,
      copy: `Nuestra tarta de queso con membrillo casero se ha convertido en la más pedida del mes. 🧀`,
      media: `https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `d12`,
      proyecto: `PLAZA EL CHANDRIO`,
      fecha: new Date(P, F, 27),
      titulo: `Martes de vermut: 2x1 hasta las 14h`,
      copy: `Todos los martes, vermut de la casa al 2x1 hasta las 2 de la tarde. 🥂`,
      media: `https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `n11`,
      proyecto: `TEATRO ALICANTE`,
      fecha: new Date(P, F, 19),
      titulo: `El equipo al completo antes del estreno`,
      copy: `Nervios, ilusión y mucho talento. Esta noche hay magia sobre el escenario 🎭✨`,
      media: `https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `n12`,
      proyecto: `PREVENIDOS Y ACCION`,
      fecha: new Date(P, F, 24),
      titulo: `Voluntarios del mes — ¡gracias!`,
      copy: `Gracias a estas personas increíbles que hacen posible nuestro proyecto cada semana ❤️🙌`,
      media: `https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `n13`,
      proyecto: `GLOBALY LIVE`,
      fecha: new Date(P, F, 29),
      titulo: `El público que nos hace grandes`,
      copy: `3.000 personas que lo dieron todo. Esto es por vosotros 🔥🎤`,
      media: `https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `d3`,
      proyecto: `GLOBALY LIVE`,
      fecha: new Date(P, F, 9),
      titulo: `Concierto en directo este sábado — entrada libre`,
      copy: `🎵 Este sábado música en vivo desde las 20h. Acceso libre hasta completar aforo.`,
      media: `https://www.youtube.com/watch?v=ZbZSe6N_BXs`,
      tipo: `video`,
      estado: ``,
    },
    {
      id: `d6`,
      proyecto: `TEATRO ALICANTE`,
      fecha: new Date(P, F, 18),
      titulo: `Estreno: "La noche de los sueños" — viernes 18`,
      copy: `Una historia de amor, memoria y segundas oportunidades. 🎭`,
      media: `https://www.youtube.com/watch?v=LXb3EKWsInQ`,
      tipo: `video`,
      estado: ``,
    },
    {
      id: `d11`,
      proyecto: `GLOBALY LIVE`,
      fecha: new Date(P, F, 20),
      titulo: `Recap del concierto del sábado 🔥`,
      copy: `Qué noche más especial. Gracias a todos los que vinisteis. ❤️🎶`,
      media: `https://www.youtube.com/watch?v=09R8_2nJtjg`,
      tipo: `video`,
      estado: ``,
    },
    {
      id: `n8`,
      proyecto: `GASTRO LEAGUE`,
      fecha: new Date(P, F, 5),
      titulo: `Vídeo: Así elaboramos nuestro pan de masa madre`,
      copy: `72 horas de fermentación. No hay atajos para el sabor real 🍞🔥`,
      media: `https://www.youtube.com/watch?v=kJQP7kiw5Fk`,
      tipo: `video`,
      estado: ``,
    },
    {
      id: `n9`,
      proyecto: `LA CRUZ DE CELIA`,
      fecha: new Date(P, F, 14),
      titulo: `Vídeo: Cómo nace una pieza artesanal`,
      copy: `De la materia prima a tus manos. Este proceso nos lleva 3 días ✂️🧵`,
      media: `https://www.youtube.com/watch?v=JGwWNGJdvx8`,
      tipo: `video`,
      estado: ``,
    },
    {
      id: `n10`,
      proyecto: `TÁVORA TEATRO ABIERTO`,
      fecha: new Date(P, F, 23),
      titulo: `Vídeo: Sevilla desde el aire al amanecer`,
      copy: `Así se ve nuestra ciudad a las 6 de la mañana. Un regalo para los que madrugan 🌅`,
      media: `https://www.youtube.com/watch?v=OPf0YbXqDm0`,
      tipo: `video`,
      estado: ``,
    },
    {
      id: `n0`,
      proyecto: `EL CHANDRIO GROUP`,
      fecha: new Date(P, F, 3),
      titulo: `Reel: 2025 en 30 segundos`,
      copy: `Un año que no para. Desliza hacia arriba 🚀`,
      media: `https://www.youtube.com/watch?v=9bZkp7q19f0`,
      tipo: `reel`,
      estado: ``,
    },
    {
      id: `n1`,
      proyecto: `PREVENIDOS Y ACCION`,
      fecha: new Date(P, F, 6),
      titulo: `Reel: RCP en 4 pasos — guarda este vídeo`,
      copy: `Comparte. Puede salvar una vida 🚨 Solo necesitas saber esto.`,
      media: `https://www.youtube.com/watch?v=fJ9rUzIMcZQ`,
      tipo: `reel`,
      estado: ``,
    },
    {
      id: `n2`,
      proyecto: `DEL POBLE FEST`,
      fecha: new Date(P, F, 10),
      titulo: `Reel: El cartel cobra vida 🎪`,
      copy: `Sonido al máximo 🔊 Ya queda menos para el mejor festival del año.`,
      media: `https://www.youtube.com/watch?v=oHg5SJYRHA0`,
      tipo: `reel`,
      estado: ``,
    },
    {
      id: `d10`,
      proyecto: `GASTRO LEAGUE`,
      fecha: new Date(P, F, 13),
      titulo: `Reel: El plato del día en tiempo récord`,
      copy: `Mira cómo montamos un pulpo a la gallega en 45 segundos 🐙⚡`,
      media: `https://www.youtube.com/watch?v=3AAdKl1UYZs`,
      tipo: `reel`,
      estado: ``,
    },
    {
      id: `n14`,
      proyecto: `PLAZA EL CHANDRIO`,
      fecha: new Date(P, F, 17),
      titulo: `Reel: ¿Eres de vermut o de caña?`,
      copy: `La pregunta del millón 🍻 Comenta abajo y debatimos.`,
      media: `https://www.youtube.com/watch?v=CevxZvSJLk8`,
      tipo: `reel`,
      estado: ``,
    },
    {
      id: `n15`,
      proyecto: `LA CRUZ DE CELIA`,
      fecha: new Date(P, F, 26),
      titulo: `Reel: Lookbook en movimiento — otoño 2026`,
      copy: `Las piezas de esta temporada merec­en verse en movimiento 🍂✨`,
      media: `https://www.youtube.com/watch?v=dQw4w9WgXcQ`,
      tipo: `reel`,
      estado: ``,
    },
    {
      id: `n3`,
      proyecto: `TEATRO ALICANTE`,
      fecha: new Date(P, F, 8),
      titulo: `Carrusel: Detrás de los bastidores del estreno`,
      copy: `Lo que no ves antes del telón. Así es el backstage real 🎭 Desliza →`,
      media: `https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900&q=80, https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=900&q=80, https://images.unsplash.com/photo-1540039155733-5bb30b4f80e7?w=900&q=80, https://images.unsplash.com/photo-1574790398664-0cb4f5b8c80a?w=900&q=80`,
      tipo: `carrusel`,
      estado: ``,
    },
    {
      id: `n4`,
      proyecto: `LA CRUZ DE CELIA`,
      fecha: new Date(P, F, 11),
      titulo: `Carrusel: Lookbook otoño — 10 looks`,
      copy: `¿Con cuál te quedas? Guarda el que más te guste y etiqueta a alguien 🍂`,
      media: `https://images.unsplash.com/photo-1483985988355-763728e1935b?w=900&q=80, https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=900&q=80, https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=900&q=80, https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=900&q=80`,
      tipo: `carrusel`,
      estado: ``,
    },
    {
      id: `n5`,
      proyecto: `EL CHANDRIO GROUP`,
      fecha: new Date(P, F, 16),
      titulo: `Carrusel: El equipo detrás del grupo`,
      copy: `Las personas que hacen posible todo esto cada día 💚 Desliza para conocernos.`,
      media: `https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=900&q=80, https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=900&q=80, https://images.unsplash.com/photo-1559060017-445fb9313ede?w=900&q=80`,
      tipo: `carrusel`,
      estado: ``,
    },
    {
      id: `n6`,
      proyecto: `GASTRO LEAGUE`,
      fecha: new Date(P, F, 21),
      titulo: `Carrusel: Los 5 platos del mes de agosto`,
      copy: `Agosto sabe así 🌞 Nuestras propuestas favoritas. ¿Cuál es la tuya?`,
      media: `https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=900&q=80, https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=80, https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=900&q=80, https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=900&q=80, https://images.unsplash.com/photo-1540189549336-e6e99eb4b45f?w=900&q=80`,
      tipo: `carrusel`,
      estado: ``,
    },
    {
      id: `n7`,
      proyecto: `GLOBALY LIVE`,
      fecha: new Date(P, F, 28),
      titulo: `Carrusel: 12 momentos del mes`,
      copy: `12 momentos, 12 fotos, 1 mes que no olvidaremos 📸 Desliza hasta el final 👉`,
      media: `https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=900&q=80, https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=900&q=80, https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=900&q=80, https://images.unsplash.com/photo-1429514513361-8fa32282fd5f?w=900&q=80`,
      tipo: `carrusel`,
      estado: ``,
    },
    {
      id: `n16`,
      proyecto: `DEL POBLE FEST`,
      fecha: new Date(P, F, 30),
      titulo: `Carrusel: Así fue el último día del festival`,
      copy: `Fin de fiesta. Gracias a todos. Nos vemos el año que viene 🎉🎪`,
      media: `https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=900&q=80, https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=900&q=80, https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=900&q=80`,
      tipo: `carrusel`,
      estado: ``,
    },
    {
      id: `x1`,
      proyecto: `CANDELA ALICANTE`,
      fecha: new Date(P, F, 15),
      titulo: `Apertura de temporada en Candela`,
      copy: `¡Abrimos puertas! Esta noche empieza la mejor temporada de nuestra historia 🕯️🎶`,
      media: `https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `x2`,
      proyecto: `CLUB GARRISON ALICANTE`,
      fecha: new Date(P, F, 15),
      titulo: `Noche de gala — reservas abiertas`,
      copy: `Dress code: elegante. Ambiente: exclusivo. Esta noche, Garrison es tuyo 🥂✨`,
      media: `https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `x3`,
      proyecto: `CLUB TEMERARIA`,
      fecha: new Date(P, F, 15),
      titulo: `Reel: La tribu temeraria al completo`,
      copy: `Una noche, una familia, una movida 🖤🔥 Desliza hacia arriba`,
      media: `https://www.youtube.com/watch?v=9bZkp7q19f0`,
      tipo: `reel`,
      estado: ``,
    },
    {
      id: `x4`,
      proyecto: `MARTINICA BAR`,
      fecha: new Date(P, F, 15),
      titulo: `Cócteles de la semana — carta nueva`,
      copy: `Mojito de maracuyá, daiquiri de frutos rojos y nuestro clásico Martinica Sour 🍹🌴`,
      media: `https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `x5`,
      proyecto: `TERRAZA DUNA`,
      fecha: new Date(P, F, 15),
      titulo: `Atardecer en Duna — puro plan`,
      copy: `El mar, el sol bajando y una copa en la mano. Hay cosas que no tienen precio 🌅`,
      media: `https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `x6`,
      proyecto: `EL CHANDRIO GROUP`,
      fecha: new Date(P, F, 15),
      titulo: `El grupo cumple 10 años — fiesta el día 15`,
      copy: `10 años de historia, de familia y de hacer lo que amamos. Esta noche brindamos con todos vosotros 🎉💚`,
      media: `https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=900&q=80`,
      tipo: `imagen`,
      estado: ``,
    },
    {
      id: `h0`,
      proyecto: `GASTRO LEAGUE`,
      fecha: new Date(P, F, 4),
      titulo: `Historia: Especial del día — pulpo a la gallega`,
      copy: `¡Solo hasta las 16h! Ven antes de que se acabe 🐙`,
      media: `https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=900&q=80`,
      tipo: `historia`,
      estado: ``,
    },
    {
      id: `h1`,
      proyecto: `TEATRO ALICANTE`,
      fecha: new Date(P, F, 17),
      titulo: `Historia: Cuenta atrás — 3 días para el estreno`,
      copy: `¡Ya queda poquito! Os mandamos mucha energía desde los camerinos 🎭`,
      media: `https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900&q=80`,
      tipo: `historia`,
      estado: ``,
    },
    {
      id: `h2`,
      proyecto: `GLOBALY LIVE`,
      fecha: new Date(P, F, 9),
      titulo: `Historia: Soundcheck en directo ahora mismo`,
      copy: `Estamos preparando algo especial para esta noche 🎶 Os vemos pronto.`,
      media: `https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=900&q=80`,
      tipo: `historia`,
      estado: ``,
    },
    {
      id: `h3`,
      proyecto: `PLAZA EL CHANDRIO`,
      fecha: new Date(P, F, 12),
      titulo: `Historia: ¿Qué queréis ver en la carta de otoño?`,
      copy: `Encuesta 👆 Tu voto cuenta para el menú de temporada 🍂`,
      media: `https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80`,
      tipo: `historia`,
      estado: ``,
    },

]

const rawRequests = [
  {
    id: `r0`,
    proyecto: `GASTRO LEAGUE`,
    fecha: new Date(),
    titulo: `Post inauguración menú de verano`,
    info: `Queremos anunciar el nuevo menú con foco en productos locales y de temporada.`,
    solicitante: `Carlos M.`,
    estado: `Aprobado`,
    tipo: `imagen`,
    canal: `Instagram`,
  },
  {
    id: `r1`,
    proyecto: `TEATRO ALICANTE`,
    fecha: new Date(new Date().setDate(new Date().getDate() + 5)),
    titulo: `Vídeo promocional obra de julio`,
    info: `Vídeo corto para redes sobre la obra de este mes. Tono emotivo.`,
    solicitante: `Ana P.`,
    estado: `En revisión`,
    tipo: `video`,
    canal: `Instagram`,
  },
  {
    id: `r2`,
    proyecto: `TEATRO SEVILLA`,
    fecha: new Date(new Date().setDate(new Date().getDate() + 10)),
    titulo: `Post ruta turística especial verano`,
    info: `Ruta temática por el Albaicín. Queremos llegar a turistas nacionales.`,
    solicitante: `Pedro L.`,
    estado: `Pendiente`,
    tipo: `imagen`,
    canal: `Facebook`,
  },
  {
    id: `r3`,
    proyecto: `PREVENIDOS Y ACCION`,
    fecha: new Date(new Date().setDate(new Date().getDate() + 15)),
    titulo: `Infografía prevención verano`,
    info: `Medidas de seguridad en la playa. Estilo visual limpio, colores claros.`,
    solicitante: `María G.`,
    estado: `Pendiente`,
    tipo: `imagen`,
    canal: `LinkedIn`,
  },

]

const CANAL_BY_TIPO = { imagen: 'Instagram', video: 'Facebook', reel: 'TikTok', carrusel: 'Instagram', historia: 'Instagram', texto: 'LinkedIn' }
const today = new Date(P, F, now.getDate())

export const demoPublications = rawPublications.map((p, i) => ({
  ...p,
  canal: p.canal || CANAL_BY_TIPO[p.tipo] || 'Instagram',
  estado: p.estado || (p.fecha < today ? 'Publicado' : i % 5 === 3 ? 'Borrador' : 'Programado'),
  promocionado: 'No',
  presupuesto: '',
  url_post: '',
}))

export const demoRequests = rawRequests.map((r, i) => ({
  ...r,
  prioridad: ['Media', 'Alta', 'Baja', 'Muy alta'][i % 4],
  contenido: r.contenido || '',
  promocionado: 'No',
  presupuesto: '',
}))
